/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioIcon: typeof import('./src/components/icons/AudioIcon.vue')['default']
    EffectIcon: typeof import('./src/components/icons/EffectIcon.vue')['default']
    EffectsIcon: typeof import('./src/components/icons/EffectsIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCollpse: typeof import('element-plus/es')['ElCollpse']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import('element-plus/es')['ElOptions']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FilterIcon: typeof import('./src/components/icons/FilterIcon.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ImageIcon: typeof import('./src/components/icons/ImageIcon.vue')['default']
    Resource: typeof import('./src/components/Resource.vue')['default']
    ResourceItem: typeof import('./src/components/ResourceItem.vue')['default']
    ResourceItemList: typeof import('./src/components/ResourceItemList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    TextIcon: typeof import('./src/components/icons/TextIcon.vue')['default']
    TransitionIcon: typeof import('./src/components/icons/TransitionIcon.vue')['default']
    VideoEdit: typeof import('./src/components/VideoEdit.vue')['default']
    VideoIcon: typeof import('./src/components/icons/VideoIcon.vue')['default']
  }
}
